version: '3.9'
services:
    backend:
        build: .
        ports:
            - "8090:8000"
        volumes:
            - .:/ImageIntervationProject
        depends_on:
            - db

    db:
        image: mysql:8
        environment:
            MYSQL_DATABASE: imageintervationproject
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
        ports:
            - "33068:3306"

